# Generated by Django 5.2.7 on 2025-10-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20251024_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='accounts/default_profile.png', null=True, upload_to='avatars/'),
        ),
    ]
